### ISSUE TITLE
[bug] Import/export subnet feature: what about organizations?

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-ipam#101]
After checking the code I do not understand whether the information of an organization is included or not, it seems to me that it's not included.

We must ensure that the organization slug of a subnet must be present when exporting and importing.
An empty cell will mean no organization.

The README doesn't mention this and should be updated accordingly.

Related to https://github.com/openwisp/openwisp-ipam/issues/99.

**Comment by purhan** [comment]
@nemesisdesign Currently, we have separate logic for subnet creation and subnet import.
Instead of handling it ourselves, do you think it's a good option to do it the following way?
- Subnet import endpoint will only extract the form data from the CSV, but will not create the subnet object itself
- It will then send this data to the `SubnetListCreateView` which already has the authentication in place

What do you think?

**Comment by pandafy** [comment]
The solution suggested by Purhan looks good, but it could add HTTP overhead for creating individual subnet.

**Comment by nemesisdesign** [comment]
Sorry I missed that comment, no I don't think we should do that, it won't scale. We could try to make the same logic which checks the organization reusable though, if possible.
