### ISSUE TITLE
[deps] Conflict swapper module between utils and ipam repos

### ISSUE THREAD

**Issue by DavidMeu** [openwisp/openwisp-ipam#125]
Trying to install master IPAM:
`git+git://github.com/openwisp/openwisp-ipam@master#egg=openwisp_ipam`
```
    openwisp-ipam 0.2 depends on swapper~=1.1.0
    openwisp-utils[rest] 0.8a0 depends on swapper~=1.3.0
```
Before the change it was `swapper~=1.1` so it was compatible with `1.*` so [swapper~=1.3.0](https://github.com/openwisp/openwisp-utils/blob/master/setup.py#L47) was good to go.
Also see:
https://www.python.org/dev/peps/pep-0440/#compatible-release

So I assume we want to make the adjustments here (revert to `swapper~=1.1`).

Opened a matching issue in [openwisp-utils](https://github.com/openwisp/openwisp-utils/issues/269)

**Comment by DavidMeu** [comment]
@nemesisdesign 
Please see if you can revert this:
https://github.com/openwisp/openwisp-ipam/commit/f352f1876cb502a2677a2eb2cba515df9ef30c6f

**Comment by pandafy** [comment]
Hello @DavidMeu and thank you for taking out time to open this issue. 
The `swapper` dependency has been centralised in openwisp-utils, since all modules of OpenWISP requires them.
Here we will only need to remove the swapper dependency so that whatever is required by openwisp-utils is installed. 

The changes done in https://github.com/openwisp/openwisp-ipam/commit/f352f1876cb502a2677a2eb2cba515df9ef30c6f were intentional. We only want to allow `micro`releases to get applied automatically.

**Comment by DavidMeu** [comment]
> Here we will only need to remove the swapper dependency so that whatever is required by openwisp-utils is installed.
So a fix will the current [swapper dependency](https://github.com/openwisp/openwisp-ipam/blob/master/requirements.txt#L6) will be removed?

**Comment by pandafy** [comment]
> So a fix will the current [swapper dependency](https://github.com/openwisp/openwisp-ipam/blob/master/requirements.txt#L6) will be removed?

Yes!

**Comment by DavidMeu** [comment]
@pandafy 
10x!
Would really appriciate if you can push it to master ASAP.
